model_dir: /mnt/f/cryovit-data/foundation_models
data_dir: /mnt/f/cryovit-data
exp_dir: /mnt/f/cryovit-data/results
results_dir: ${paths.exp_dir}

# tomo_name: ???
# feature_name: ???
# dino_name: ???
# sam_name: ???
# csv_name: ???
# split_name: ???

#### DO NOT CHANGE ####

defaults:
  - base_env